### ISSUE TITLE
Cannot find module 'laravel-elixir/ingredients/helpers/utilities'

### ISSUE THREAD

**Issue by loranger** [nathanmac/laravel-elixir-imagemin#1]
It seems elixir structure has changed for Laravel 5 and utilities is no more an helper.
I was able to make it work again by changing the utilities var definition in index.js, line 8

``` javascript
var utilities = require('laravel-elixir/ingredients/commands/Utilities');
```

**Comment by nathanmac** [comment]
Thanks, I've pushed you changes :+1:

**Comment by loranger** [comment]
I'm afraid I can't get your commit.

I've just created a new laravel 5 projet, but laravel-elixir-imagemin still can't find the utilities module.
Did you pushed your commit ?
Maybe you plan to make a l5 branch or maybe a tag ?

**Comment by nathanmac** [comment]
Looks like the utilities path change in elixir.

The cause should be [cb1f7c5b676870460a4e1ffb8e79a6a4bb16d114](https://github.com/laravel/elixir/commit/cb1f7c5b676870460a4e1ffb8e79a6a4bb16d114) in laravel/elixir.
